[env]
  TERM="xterm-256color"
# The definition of color schemes.
[selection]
  save_to_clipboard=true

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[window]
opacity = 0.95
decorations = "none"
startup_mode = "Windowed"
dynamic_title = true

  [window.dimensions]
  columns = 110
  lines = 40

  [window.padding]
  x = 4
  y = 0

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 17

  [font.normal]
  family = "FiraCode Nerd Font"
  style = "Regular"

  [font.bold]
  family = "FiraCode Nerd Font"
  style = "Bold"

  [font.italic]
  family = "FiraCode Nerd Font"
  style = "Italic"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[shell]
program = "/opt/homebrew/bin/tmux"

